### ISSUE TITLE
Question: copy login command

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb-gitops-docs#4]
See: https://github.com/bcgov/bcbb-gitops-docs/blob/main/docs/01-bcgov-platform.md

“Once you are logged into the OpenShift console you can select "Copy login command" under your profile name.”

Q: What is the significance of the last line? …what is the copied command needed for?

**Comment by sylus** [comment]
Hey @NicoledeGreef so these docs were some rough notes I had as I was doing the initial prototype.

This is needed when you want to execute either kubectl or the oc cli in order to interact with the cluster.

I can update the notes and add a little context around this and other things.

**Comment by sylus** [comment]
Resolved this in my updates notes :D
